### ISSUE TITLE
Issues with dark mode inversions

### ISSUE THREAD

**Issue by ToSMaverick** [binokochumolvarghese/lightbi-hugo#76]
First of all, thank you for your efforts!
I really like the minimal yet smooth design of this theme!

I want to convert my portfolio site (michaelfischer.at) to a static hugo site. It's a rather simple site but I need a carousel and a gallery with a lightbox. After a little bit of research I wanted to give [hugo-shortcode-gallery](https://github.com/mfg92/hugo-shortcode-gallery) a try. For the carousel I settled on plain HTML via [rawhtml](https://www.scivision.dev/hugo-raw-html/).

This led to 3 issues:
1. The contrast of the images in the carousel was reduced due to the double inversion in main.scss
2. The tumbnails from the shortcode-gallery were inverted because they also use the "filter" function for the blur effect
3. The lightbox of the gallery became white because it was inverted as well

I guess setting proper colors for the dark mode will be doubling the code base. I'm scratching my head but I can't think of another solution 🤔  

```css
/* --- Dark mode --- */

:root[data-theme="dark"] {
  background-color: #171717 !important;
  filter: invert(100%) hue-rotate(180deg) brightness(105%) contrast(85%);
  -webkit-filter: invert(100%) hue-rotate(180deg) brightness(105%) contrast(85%);
}
:root[data-theme="dark"] body {
  background-color: #FFF !important;
}
:root[data-theme="dark"] img,
:root[data-theme="dark"] video,
:root[data-theme="dark"] iframe,
:root[data-theme="dark"] body [style*="background-image"] {
  filter: hue-rotate(180deg) contrast(100%) invert(100%);
  -webkit-filter: hue-rotate(180deg) contrast(100%) invert(100%);
}
:root[data-theme="dark"] #dark-mode-toggle::before {
  /* Convert to .bi-sun */
  content: "\f5a2";
}
```

**Comment by ToSMaverick** [comment]
I was able to workaround the issue with the tweaks below. Certainly still work to be done but suffucient for my homepage. It's already online with your template!

```css
/* --- Dark mode --- */

:root[data-theme="dark"] {
  background-color: #121212 !important;
  color: #e0e0e0 !important;
  --link-color: #bb86fc;
  --border-color: #333333;
  --button-bg-color: #1f1f1f;
  --button-text-color: #e0e0e0;
}
:root[data-theme="dark"] body {
  background-color: #121212 !important;
  color: #e0e0e0;
}

:root[data-theme="dark"] .navbar {
  background-color: #121212 !important;
  box-shadow: 0px 2px 20px 0px rgba(255, 255, 255, 0.08);
  color: #e0e0e0;
}

:root[data-theme="dark"] .nav-link, .navbar-brand {
  background-color: #121212 !important;
  color: #e0e0e0;
}

:root[data-theme="dark"] footer {
  background-color: #1a1a1a;
  border-top: 1px #3f3f3f solid;
}

:root[data-theme="dark"] #dark-mode-toggle::before {
  /* Convert to .bi-sun */
  content: "\f5a2";
}
```
